# Generated by Django 3.2 on 2021-04-23 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OMOPAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='concept',
            table='concept',
        ),
    ]
