# Generated by Django 3.2 on 2021-04-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMOPAPI', '0002_alter_concept_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('vocabulary_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('vocabulary_name', models.CharField(max_length=255)),
                ('vocabulary_reference', models.CharField(max_length=255)),
                ('vocabulary_version', models.CharField(blank=True, max_length=255, null=True)),
                ('vocabulary_concept_id', models.IntegerField()),
            ],
            options={
                'db_table': 'vocabulary',
                'managed': False,
            },
        ),
    ]
