# Generated by Django 3.2 on 2021-04-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMOPAPI', '0003_vocabulary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptRelationship',
            fields=[
                ('concept_id_1', models.IntegerField(primary_key=True, serialize=False)),
                ('concept_id_2', models.IntegerField()),
                ('relationship_id', models.CharField(max_length=20)),
                ('valid_start_date', models.DateField()),
                ('valid_end_date', models.DateField()),
                ('invalid_reason', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'concept_relationship',
                'managed': False,
            },
        ),
    ]
