# Generated by Django 3.2 on 2021-04-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMOPAPI', '0004_conceptrelationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptAncestor',
            fields=[
                ('ancestor_concept_id', models.IntegerField(primary_key=True, serialize=False)),
                ('descendant_concept_id', models.IntegerField()),
                ('min_levels_of_separation', models.IntegerField()),
                ('max_levels_of_separation', models.IntegerField()),
            ],
            options={
                'db_table': 'concept_ancestor',
                'managed': False,
            },
        ),
    ]
