# Generated by Django 3.2 on 2021-04-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMOPAPI', '0006_conceptclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptSynonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_id', models.IntegerField()),
                ('concept_synonym_name', models.CharField(max_length=1000)),
                ('language_concept_id', models.IntegerField()),
            ],
            options={
                'db_table': 'concept_synonym',
                'managed': False,
            },
        ),
    ]
