# Generated by Django 3.2 on 2021-04-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMOPAPI', '0007_conceptsynonym'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('domain_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('domain_name', models.CharField(max_length=255)),
                ('domain_concept_id', models.IntegerField()),
            ],
            options={
                'db_table': 'domain',
                'managed': False,
            },
        ),
    ]
