# Generated by Django 3.2 on 2021-04-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMOPAPI', '0008_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugStrength',
            fields=[
                ('drug_concept_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ingredient_concept_id', models.IntegerField()),
                ('amount_value', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('amount_unit_concept_id', models.IntegerField(blank=True, null=True)),
                ('numerator_value', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('numerator_unit_concept_id', models.IntegerField(blank=True, null=True)),
                ('denominator_value', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('denominator_unit_concept_id', models.IntegerField(blank=True, null=True)),
                ('box_size', models.IntegerField(blank=True, null=True)),
                ('valid_start_date', models.DateField()),
                ('valid_end_date', models.DateField()),
                ('invalid_reason', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'drug_strength',
                'managed': False,
            },
        ),
    ]
